version: 2.0

jobs:
  test:
    context: yourvictoria.vic.gov.au
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
          CIRCLE_TEST_REPORTS: test-results
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Lint code.
          command: yarn lint --format ./node_modules/eslint-junit/index.js 
          environment:
             ESLINT_JUNIT_OUTPUT: ./test-results/lint/eslint.xml
      - run:
          name: Unit tests
          command: yarn test:unit --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-results/unit/    
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  commit:
    jobs:  
      - test

